name: pet-health-hub
services:
  app:
    image:
      dockerfile: Dockerfile
      context: .
    domains:
      - host: your-domain.com
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - published: 80
        target: 3001
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s